.TH daudio 1 daudio\-VERSION
.SH NAME
daudio \- dynamic audio tool
.SH SYNOPSIS
.B daudio
.RB [ \-iv ]
.RB [ \-cmd
.IR inc|dec|toggle ]
.RB [ \-m
.IR monitor ]
.RB [ \-fn
.IR font ]
.RB [ \-nb
.IR color ]
.RB [ \-nf
.IR color ]
.RB [ \-sb
.IR color ]
.RB [ \-sf
.IR color ]
.RB [ \-mb
.IR color ]
.RB [ \-mf
.IR color ]
.RB [ \-w
.IR windowid ]
.P
.SH DESCRIPTION
.B daudio
is a dynamic audio tool for X. It allows the user to adjust the volume and the output sink in pulseaudio.
Only one instance can run at a time, this is handled via /tmp/daudio.pid.
.P
.SH OPTIONS
.TP
.BI \-cmd " inc|dec|toggle"
which command to execute on program start. up increases volume, down decreases volume, toggle (un-)mutes.
.TP
.BI \-i
interactive mode. Grabs keyboard.
.TP
.BI \-m " monitor"
daudio is displayed on the monitor number supplied. Monitor numbers are starting
from 0.
.TP
.BI \-fn " font"
defines the font or font set used.
.TP
.BI \-nb " color"
defines the normal background color.
.IR #RGB ,
.IR #RRGGBB ,
and X color names are supported.
.TP
.BI \-nf " color"
defines the normal foreground color.
.TP
.BI \-sb " color"
defines the selected background color.
.TP
.BI \-sf " color"
defines the selected foreground color.
.TP
.BI \-mb " color"
defines the muted background color.
.TP
.BI \-mf " color"
defines the muted foreground color.
.TP
.B \-v
prints version information to stdout, then exits.
.TP
.BI \-w " windowid"
embed into windowid.
.SH USAGE
In interactive mode, daudio is completely controlled by the keyboard. Volume is adjusted via the arrow keys left/right,
output devices are selected using the arrow keys up/down.

.TP
.B Return
Confirm output device selection.

.SH SEE ALSO
.IR dwm (1)
