#! /bin/sh

# list individual apps
echo "==============="
echo "Running Apps"
pacmd list-sink-inputs | awk '/index/ || /application.name /'

# list all sound device
echo "==============="
echo "Sound Devices"
pacmd list-sinks | awk '/index/ || /name:/'
